# 默认使用开发配置
spring:
  profiles:
    active: dev

#配置mybatis参数
mybatis:
  type-aliases-package: com.zcz.entity
  mapper-locations: classpath:mapper/*.xml

---

#开发配置
spring:
  profiles: dev

  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    url: jdbc:mysql://192.168.1.53:3306/hnquxian?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    password: Kopo6311



server:
  port: 6060
